// This source code is licensed under the BSD-3 license found in the LICENSE file in the root directory of this source tree.
// © 2024-2026, University of Bern, Space Research and Planetary Sciences, Physics Institute, Rafael Ottersberg

// Portions of this code were derived from NVIDIA OptiX sample code.
// See THIRD_PARTY_NOTICES.md for full license text.

#include <optix.h>
#include <optix_stack_size.h>
#include <optix_function_table_definition.h>

#include "raytracing_pipeline.h"
#include "photontracer.h"
#include "photontracer_kernels.h" // generated by embed_cuda at compile time

#include <OptiXToolkit/Error/cudaErrorCheck.h>
#include <OptiXToolkit/Error/optixErrorCheck.h>

#include <chrono>

template <typename T>
struct SbtRecord
{
    __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
    T data;
};

typedef SbtRecord<RayGenData> RayGenSbtRecord;
typedef SbtRecord<MissData> MissSbtRecord;
typedef SbtRecord<HitGroupData> HitGroupSbtRecord;
typedef SbtRecord<HitGroupDataDensity> HitGroupSbtRecordDensity;

long currentTimeMs()
{
    using namespace std::chrono;
    return duration_cast<milliseconds>(high_resolution_clock::now().time_since_epoch()).count();
}

void RayTracingPipeline::initialize(const OptixDeviceContext context, const GeometryType geometryType, std::vector<Material> materials, const float wavelengthUm, uint32_t maxTraversableGraphDepth)
{
    maxTraversableGraphDepth_ = maxTraversableGraphDepth;
    setupPipelineCompileOptions(geometryType);
    createModules(context);
    createProgramGroups(context);
    linkPipeline(context);
    setupShaderBindingTable(materials, wavelengthUm);
}

void RayTracingPipeline::updateShaderBindingTable(const std::vector<Material> materials, const float wavelengthUm)
{
    if (!sbtInitialized_)
    {
        throw std::runtime_error("Shader Binding Table not initialized. Call setupShaderBindingTable() first.");
    }
    cleanupShaderBindingTable();
    setupShaderBindingTable(materials, wavelengthUm);
}

void RayTracingPipeline::launch(InputParameters &params, uint3 launchDim)
{
    if (!pipeline_)
    {
        throw std::runtime_error("Pipeline not created. Call initialize() first.");
    }
    CUstream stream;
    OTK_ERROR_CHECK(cudaStreamCreate(&stream));
    CUdeviceptr dParam;
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&dParam), sizeof(InputParameters)));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(dParam),
        &params, sizeof(params),
        cudaMemcpyHostToDevice));

    long long t0 = currentTimeMs();
    OTK_ERROR_CHECK(optixLaunch(pipeline_, stream, dParam, sizeof(InputParameters), &sbt_, launchDim.x, launchDim.y, launchDim.z));
    OTK_CUDA_SYNC_CHECK();
    long long t1 = currentTimeMs();
    std::cout << "Finished raytracing in " << t1 - t0 << " ms" << std::endl;
    OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(dParam)));
    OTK_ERROR_CHECK(cudaStreamDestroy(stream));
}

RayTracingPipeline::~RayTracingPipeline()
{
    if (sbtInitialized_)
    {
        cleanupShaderBindingTable();
        sbtInitialized_ = false;
    }
    if (pipelineCompileOptionsInitialized_)
    {
        pipelineCompileOptions_ = {};
        pipelineCompileOptionsInitialized_ = false;
    }
    if (pipeline_)
    {
        OTK_ERROR_CHECK(optixPipelineDestroy(pipeline_));
        pipeline_ = nullptr;
    }
    if (raygenProgGroup_)
    {
        OTK_ERROR_CHECK(optixProgramGroupDestroy(raygenProgGroup_));
        raygenProgGroup_ = nullptr;
    }
    if (missProgGroup_)
    {
        OTK_ERROR_CHECK(optixProgramGroupDestroy(missProgGroup_));
        missProgGroup_ = nullptr;
    }
    if (hitgroupProgGroup_)
    {
        OTK_ERROR_CHECK(optixProgramGroupDestroy(hitgroupProgGroup_));
        hitgroupProgGroup_ = nullptr;
    }
    if (module_)
    {
        OTK_ERROR_CHECK(optixModuleDestroy(module_));
        module_ = nullptr;
    }
}

void RayTracingPipeline::setupPipelineCompileOptions(GeometryType geometryType)
{
    OptixPrimitiveTypeFlags primitiveTypeFlags;

    pipelineCompileOptions_.usesMotionBlur = false;
    pipelineCompileOptions_.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_ANY;
    pipelineCompileOptions_.numPayloadValues = 22;
    pipelineCompileOptions_.numAttributeValues = 3;
    pipelineCompileOptions_.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
    pipelineCompileOptions_.pipelineLaunchParamsVariableName = "params";
    pipelineCompileOptions_.usesPrimitiveTypeFlags = OPTIX_PRIMITIVE_TYPE_FLAGS_TRIANGLE;

    pipelineCompileOptionsInitialized_ = true;
}

void RayTracingPipeline::createModules(const OptixDeviceContext context)
{
    if (!pipelineCompileOptionsInitialized_)
    {
        throw std::runtime_error("Pipeline compile options not initialized. Call setupPipelineCompileOptions() first.");
    }
    OptixModuleCompileOptions moduleCompileOptions = {};
#if !defined(NDEBUG)
    moduleCompileOptions.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_0;
    moduleCompileOptions.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_FULL;
    moduleCompileOptions.maxRegisterCount = 255; // Temporary workaround for issue with segfault during module creation
    std::cout << "Start optixModuleCreate" << std::endl;
#endif
    OTK_ERROR_CHECK_LOG(optixModuleCreate(
        context,
        &moduleCompileOptions,
        &pipelineCompileOptions_,
        photontracerCudaText(),
        photontracerCudaSize,
        LOG, &LOG_SIZE,
        &module_));
#if !defined(NDEBUG)
    std::cout << "Finished optixModuleCreate" << std::endl;
#endif

}

void RayTracingPipeline::createProgramGroups(const OptixDeviceContext context)
{
    if (!module_)
    {
        throw std::runtime_error("Module not created. Call createModules() first.");
    }
    {
        OptixProgramGroupOptions programGroupOptions = {}; // Initialize to zeros

        OptixProgramGroupDesc raygenProgGroupDesc = {}; //
        raygenProgGroupDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
        raygenProgGroupDesc.raygen.module = module_;
        raygenProgGroupDesc.raygen.entryFunctionName = "__raygen__rg";
        OTK_ERROR_CHECK_LOG(optixProgramGroupCreate(
            context,
            &raygenProgGroupDesc,
            1, // num program groups
            &programGroupOptions,
            LOG, &LOG_SIZE,
            &raygenProgGroup_));

        OptixProgramGroupDesc missProgGroupDesc = {};
        missProgGroupDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
        missProgGroupDesc.miss.module = module_;
        missProgGroupDesc.miss.entryFunctionName = "__miss__ms";
        OTK_ERROR_CHECK_LOG(optixProgramGroupCreate(
            context,
            &missProgGroupDesc,
            1, // num program groups
            &programGroupOptions,
            LOG, &LOG_SIZE,
            &missProgGroup_));

        OptixProgramGroupDesc hitgroupProgGroupDesc = {};
        hitgroupProgGroupDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
        hitgroupProgGroupDesc.hitgroup.moduleCH = module_;
        hitgroupProgGroupDesc.hitgroup.entryFunctionNameCH = "__closesthit__ch";

        OTK_ERROR_CHECK_LOG(optixProgramGroupCreate(
            context,
            &hitgroupProgGroupDesc,
            1, // num program groups
            &programGroupOptions,
            LOG, &LOG_SIZE,
            &hitgroupProgGroup_));
    }
}

void RayTracingPipeline::linkPipeline(const OptixDeviceContext context)
{
    if (!pipelineCompileOptionsInitialized_)
    {
        throw std::runtime_error("Pipeline compile options not initialized. Call setupPipelineCompileOptions() first.");
    }
    if (!raygenProgGroup_ || !missProgGroup_ || !hitgroupProgGroup_)
    {
        throw std::runtime_error("Program Groups not created. Call createProgramGroups() first.");
    }
    {
        OptixProgramGroup programGroups[] = {raygenProgGroup_, missProgGroup_, hitgroupProgGroup_};

        const uint32_t cMaxTraceDepth = 1; // no recursion, we use iterative path tracing

        OptixPipelineLinkOptions pipelineLinkOptions = {};
        pipelineLinkOptions.maxTraceDepth = cMaxTraceDepth;
        OTK_ERROR_CHECK_LOG(optixPipelineCreate(
            context,
            &pipelineCompileOptions_,
            &pipelineLinkOptions,
            programGroups,
            sizeof(programGroups) / sizeof(programGroups[0]),
            LOG, &LOG_SIZE,
            &pipeline_));

        OptixStackSizes stackSizes = {};
        for (auto &progGroup : programGroups)
        {
            OTK_ERROR_CHECK(optixUtilAccumulateStackSizes(progGroup, &stackSizes, pipeline_));
        }

        uint32_t directCallableStackSizeFromTraversal;
        uint32_t directCallableStackSizeFromState;
        uint32_t continuationStackSize;
        OTK_ERROR_CHECK(optixUtilComputeStackSizes(&stackSizes, maxTraceDepth_,
                                                   0, // maxCCDepth
                                                   0, // maxDCDEpth
                                                   &directCallableStackSizeFromTraversal,
                                                   &directCallableStackSizeFromState, &continuationStackSize));

        OTK_ERROR_CHECK(optixPipelineSetStackSize(pipeline_, directCallableStackSizeFromTraversal,
                                                  directCallableStackSizeFromState, continuationStackSize,
                                                  maxTraversableGraphDepth_));
    }
}

void RayTracingPipeline::setupShaderBindingTable(const std::vector<Material> materials, const float wavelengthUm)
{
    CUdeviceptr raygenRecord;
    const size_t raygenRecordSize = sizeof(RayGenSbtRecord);
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&raygenRecord), raygenRecordSize));
    RayGenSbtRecord rgSbt;
    OTK_ERROR_CHECK(optixSbtRecordPackHeader(raygenProgGroup_, &rgSbt));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(raygenRecord),
        &rgSbt,
        raygenRecordSize,
        cudaMemcpyHostToDevice));

    CUdeviceptr missRecord;
    size_t missRecordSize = sizeof(MissSbtRecord);
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&missRecord), missRecordSize));
    MissSbtRecord msSbt;
    OTK_ERROR_CHECK(optixSbtRecordPackHeader(missProgGroup_, &msSbt));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(missRecord),
        &msSbt,
        missRecordSize,
        cudaMemcpyHostToDevice));

    CUdeviceptr hitgroupRecord;
    size_t hitgroupRecordSize = sizeof(HitGroupSbtRecord);
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&hitgroupRecord), hitgroupRecordSize));
    HitGroupSbtRecord hgSbt;

    hgSbt.data = {};
    for (size_t i = 0; i < materials.size(); ++i)
    {
        hgSbt.data.materials[i] = materials[i];
    }
    hgSbt.data.wavelengthUm = wavelengthUm;

    OTK_ERROR_CHECK(optixSbtRecordPackHeader(hitgroupProgGroup_, &hgSbt));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(hitgroupRecord),
        &hgSbt,
        hitgroupRecordSize,
        cudaMemcpyHostToDevice));

    sbt_.raygenRecord = raygenRecord;
    sbt_.missRecordBase = missRecord;
    sbt_.missRecordStrideInBytes = sizeof(MissSbtRecord);
    sbt_.missRecordCount = 1;
    sbt_.hitgroupRecordBase = hitgroupRecord;
    sbt_.hitgroupRecordStrideInBytes = sizeof(HitGroupSbtRecord);
    sbt_.hitgroupRecordCount = 1;

    sbtInitialized_ = true;
}

void RayTracingPipeline::cleanupShaderBindingTable()
{
    if (sbt_.raygenRecord)
    {
        OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(sbt_.raygenRecord)));
    }
    if (sbt_.missRecordBase)
    {
        OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(sbt_.missRecordBase)));
    }
    if (sbt_.hitgroupRecordBase)
    {
        OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(sbt_.hitgroupRecordBase)));
    }
    sbt_ = {}; // Reset the SBT to a clean state
    sbtInitialized_ = false;
}

/* Density Pipeline */

void VolumeFractionPipeline::initialize(const OptixDeviceContext context, uint32_t maxTraversableGraphDepth)
{
    maxTraversableGraphDepth_ = maxTraversableGraphDepth;
    setupPipelineCompileOptions();
    createModules(context);
    createProgramGroups(context);
    linkPipeline(context);
    setupShaderBindingTable();
}

void VolumeFractionPipeline::launch(InputParametersSampleDensity &params)
{
    if (!pipeline_)
    {
        throw std::runtime_error("Pipeline not created. Call initialize() first.");
    }
    CUstream stream;
    OTK_ERROR_CHECK(cudaStreamCreate(&stream));
    CUdeviceptr dParam;
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&dParam), sizeof(InputParametersSampleDensity)));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(dParam),
        &params, sizeof(params),
        cudaMemcpyHostToDevice));

    long long t0 = currentTimeMs();
    OTK_ERROR_CHECK(optixLaunch(pipeline_, stream, dParam, sizeof(InputParametersSampleDensity), &sbt_, params.numberOfRays, 1, 1));
    OTK_CUDA_SYNC_CHECK();
    long long t1 = currentTimeMs();
    std::cout << "Finished raytracing in " << t1 - t0 << " ms" << std::endl;
    OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(dParam)));
    OTK_ERROR_CHECK(cudaStreamDestroy(stream));
}

VolumeFractionPipeline::~VolumeFractionPipeline()
{
    if (sbtInitialized_)
    {
        cleanupShaderBindingTable();
        sbtInitialized_ = false;
    }
    if (pipelineCompileOptionsInitialized_)
    {
        pipelineCompileOptions_ = {};
        pipelineCompileOptionsInitialized_ = false;
    }
    if (pipeline_)
    {
        OTK_ERROR_CHECK(optixPipelineDestroy(pipeline_));
        pipeline_ = nullptr;
    }
    if (raygenProgGroup_)
    {
        OTK_ERROR_CHECK(optixProgramGroupDestroy(raygenProgGroup_));
        raygenProgGroup_ = nullptr;
    }
    if (missProgGroup_)
    {
        OTK_ERROR_CHECK(optixProgramGroupDestroy(missProgGroup_));
        missProgGroup_ = nullptr;
    }
    if (hitgroupProgGroup_)
    {
        OTK_ERROR_CHECK(optixProgramGroupDestroy(hitgroupProgGroup_));
        hitgroupProgGroup_ = nullptr;
    }
    if (module_)
    {
        OTK_ERROR_CHECK(optixModuleDestroy(module_));
        module_ = nullptr;
    }
}

void VolumeFractionPipeline::setupPipelineCompileOptions()
{
    OptixPrimitiveTypeFlags primitiveTypeFlags;
    primitiveTypeFlags = OPTIX_PRIMITIVE_TYPE_FLAGS_TRIANGLE;
    pipelineCompileOptions_.usesMotionBlur = false;
    pipelineCompileOptions_.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_ANY;
    pipelineCompileOptions_.numPayloadValues = 22;
    pipelineCompileOptions_.numAttributeValues = 3;
    pipelineCompileOptions_.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
    pipelineCompileOptions_.pipelineLaunchParamsVariableName = "paramsDensity";
    pipelineCompileOptions_.usesPrimitiveTypeFlags = primitiveTypeFlags;

    pipelineCompileOptionsInitialized_ = true;
}

void VolumeFractionPipeline::createModules(const OptixDeviceContext context)
{
    if (!pipelineCompileOptionsInitialized_)
    {
        throw std::runtime_error("Pipeline compile options not initialized. Call setupPipelineCompileOptions() first.");
    }
    OptixModuleCompileOptions moduleCompileOptions = {};
#if !defined(NDEBUG)
    moduleCompileOptions.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_0;
    moduleCompileOptions.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_FULL;
    moduleCompileOptions.maxRegisterCount = 140; // Temporary workaround for issue with segfault during module creation
    std::cout << "Start optixModuleCreate" << std::endl;
#endif
    OTK_ERROR_CHECK_LOG(optixModuleCreate(
        context,
        &moduleCompileOptions,
        &pipelineCompileOptions_,
        photontracerCudaText(),
        photontracerCudaSize,
        LOG, &LOG_SIZE,
        &module_));
#if !defined(NDEBUG)
    std::cout << "Finished optixModuleCreate" << std::endl;
#endif
}

void VolumeFractionPipeline::createProgramGroups(const OptixDeviceContext context)
{
    if (!module_)
    {
        throw std::runtime_error("Module not created. Call createModules() first.");
    }
    {
        OptixProgramGroupOptions programGroupOptions = {}; // Initialize to zeros

        OptixProgramGroupDesc raygenProgGroupDesc = {}; //
        raygenProgGroupDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
        raygenProgGroupDesc.raygen.module = module_;
        raygenProgGroupDesc.raygen.entryFunctionName = "__raygen__density";
        OTK_ERROR_CHECK_LOG(optixProgramGroupCreate(
            context,
            &raygenProgGroupDesc,
            1, // num program groups
            &programGroupOptions,
            LOG, &LOG_SIZE,
            &raygenProgGroup_));

        OptixProgramGroupDesc missProgGroupDesc = {};
        missProgGroupDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
        missProgGroupDesc.miss.module = module_;
        missProgGroupDesc.miss.entryFunctionName = "__miss__density";
        OTK_ERROR_CHECK_LOG(optixProgramGroupCreate(
            context,
            &missProgGroupDesc,
            1, // num program groups
            &programGroupOptions,
            LOG, &LOG_SIZE,
            &missProgGroup_));

        OptixProgramGroupDesc hitgroupProgGroupDesc = {};
        hitgroupProgGroupDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
        hitgroupProgGroupDesc.hitgroup.moduleCH = module_;
        hitgroupProgGroupDesc.hitgroup.entryFunctionNameCH = "__closesthit__density";

        OTK_ERROR_CHECK_LOG(optixProgramGroupCreate(
            context,
            &hitgroupProgGroupDesc,
            1, // num program groups
            &programGroupOptions,
            LOG, &LOG_SIZE,
            &hitgroupProgGroup_));
    }
}

void VolumeFractionPipeline::linkPipeline(const OptixDeviceContext context)
{
    if (!pipelineCompileOptionsInitialized_)
    {
        throw std::runtime_error("Pipeline compile options not initialized. Call setupPipelineCompileOptions() first.");
    }
    if (!raygenProgGroup_ || !missProgGroup_ || !hitgroupProgGroup_)
    {
        throw std::runtime_error("Program Groups not created. Call createProgramGroups() first.");
    }
    {
        OptixProgramGroup programGroups[] = {raygenProgGroup_, missProgGroup_, hitgroupProgGroup_};

        const uint32_t cMaxTraceDepth = 1; // no recursion, we use iterative path tracing

        OptixPipelineLinkOptions pipelineLinkOptions = {};
        pipelineLinkOptions.maxTraceDepth = cMaxTraceDepth;
        OTK_ERROR_CHECK_LOG(optixPipelineCreate(
            context,
            &pipelineCompileOptions_,
            &pipelineLinkOptions,
            programGroups,
            sizeof(programGroups) / sizeof(programGroups[0]),
            LOG, &LOG_SIZE,
            &pipeline_));

        OptixStackSizes stackSizes = {};
        for (auto &progGroup : programGroups)
        {
            OTK_ERROR_CHECK(optixUtilAccumulateStackSizes(progGroup, &stackSizes, pipeline_));
        }

        uint32_t directCallableStackSizeFromTraversal;
        uint32_t directCallableStackSizeFromState;
        uint32_t continuationStackSize;
        OTK_ERROR_CHECK(optixUtilComputeStackSizes(&stackSizes, maxTraceDepth_,
                                                   0, // maxCCDepth
                                                   0, // maxDCDEpth
                                                   &directCallableStackSizeFromTraversal,
                                                   &directCallableStackSizeFromState, &continuationStackSize));

        OTK_ERROR_CHECK(optixPipelineSetStackSize(pipeline_, directCallableStackSizeFromTraversal,
                                                  directCallableStackSizeFromState, continuationStackSize,
                                                  maxTraversableGraphDepth_));
    }
}

void VolumeFractionPipeline::setupShaderBindingTable()
{
    CUdeviceptr raygenRecord;
    const size_t raygenRecordSize = sizeof(RayGenSbtRecord);
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&raygenRecord), raygenRecordSize));
    RayGenSbtRecord rgSbt;
    OTK_ERROR_CHECK(optixSbtRecordPackHeader(raygenProgGroup_, &rgSbt));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(raygenRecord),
        &rgSbt,
        raygenRecordSize,
        cudaMemcpyHostToDevice));

    CUdeviceptr missRecord;
    size_t missRecordSize = sizeof(MissSbtRecord);
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&missRecord), missRecordSize));
    MissSbtRecord msSbt;
    OTK_ERROR_CHECK(optixSbtRecordPackHeader(missProgGroup_, &msSbt));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(missRecord),
        &msSbt,
        missRecordSize,
        cudaMemcpyHostToDevice));

    CUdeviceptr hitgroupRecord;
    size_t hitgroupRecordSize = sizeof(HitGroupSbtRecordDensity);
    OTK_ERROR_CHECK(cudaMalloc(reinterpret_cast<void **>(&hitgroupRecord), hitgroupRecordSize));
    HitGroupSbtRecordDensity hgSbt;

    OTK_ERROR_CHECK(optixSbtRecordPackHeader(hitgroupProgGroup_, &hgSbt));
    OTK_ERROR_CHECK(cudaMemcpy(
        reinterpret_cast<void *>(hitgroupRecord),
        &hgSbt,
        hitgroupRecordSize,
        cudaMemcpyHostToDevice));

    sbt_.raygenRecord = raygenRecord;
    sbt_.missRecordBase = missRecord;
    sbt_.missRecordStrideInBytes = sizeof(MissSbtRecord);
    sbt_.missRecordCount = 1;
    sbt_.hitgroupRecordBase = hitgroupRecord;
    sbt_.hitgroupRecordStrideInBytes = sizeof(HitGroupSbtRecordDensity);
    sbt_.hitgroupRecordCount = 1;

    sbtInitialized_ = true;
}

void VolumeFractionPipeline::cleanupShaderBindingTable()
{
    if (sbt_.raygenRecord)
    {
        OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(sbt_.raygenRecord)));
    }
    if (sbt_.missRecordBase)
    {
        OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(sbt_.missRecordBase)));
    }
    if (sbt_.hitgroupRecordBase)
    {
        OTK_ERROR_CHECK(cudaFree(reinterpret_cast<void *>(sbt_.hitgroupRecordBase)));
    }
    sbt_ = {}; // Reset the SBT to a clean state
    sbtInitialized_ = false;
}